package hibernate.hbm;
// Generated 2019-05-02 01:55:28 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;

import org.hibernate.annotations.Cache;

/**
 * Laptop generated by hbm2java
 */
@Cacheable
public class Laptop implements java.io.Serializable {

	private int idLaptop;
	private Grafika grafika;
	private Klient klient;
	private ProcesorChipset procesorChipset;
	private Sieci sieci;
	private String nazwaLaptopa;
	private String nazwaModelu;
	private String nrCzesci;
	private String plytaGlowna;
	private String pamiecRam;
	private String szybkoscPamieci;
	private String czestotliwoscTaktowaniaRam;
	private String maksymalnaPamiec;
	private String liczbaSlotowPam;
	private String czytnikKart;
	private String obslugiwanaKarta;
	private String nosnikDanych;
	private String dostepDysku;
	private String szybkoscNosnika;
	private String formatyCd;
	private String naped;
	private String szybkoscCd;
	private String przekatnaEkranu;
	private String systemKomputerowy;
	private String architekturaSystemu;
	private String klawiatura;
	private String iloscZnakow;
	private String urzadzenieWskazuj;
	private String liczbaUsb2;
	private String liczbaUsb3;
	private String wyjSluchawkowe;
	private String wejMikrofonowe;
	private String hdmi;
	private String vga;
	private String portSieciowy;
	private String inneSloty;
	private String wysSzerGleb;
	private String masa;
	private String budowaBaterii;
	private String najwCzasPracy;
	private String iloscOgniw;
	private String pojBaterii;
	private String glosniki;
	private String mikrofon;
	private String kamera;
	private String czytnikBio;
	private String kompletZaw;
	private String gwarancja;
	private String oprogramowanie;
	private BigDecimal cena;
	private String fotka;
	private int ilosc;
	private Set<Foty> foties = new HashSet<Foty>(0);
	private Set<Fotaprzednia> fotaprzednias = new HashSet<Fotaprzednia>(0);
	private Set<Zamowienie> zamowienies = new HashSet<Zamowienie>(0);

	public Laptop() {
	}

	public Laptop(int idLaptop) {
		this.idLaptop = idLaptop;
	}

	public Laptop(int idLaptop, Grafika grafika, Klient klient, ProcesorChipset procesorChipset, Sieci sieci,
			String nazwaLaptopa, String nazwaModelu, String nrCzesci, String plytaGlowna, String pamiecRam,
			String szybkoscPamieci, String czestotliwoscTaktowaniaRam, String maksymalnaPamiec, String liczbaSlotowPam,
			String czytnikKart, String obslugiwanaKarta, String nosnikDanych, String dostepDysku,
			String szybkoscNosnika, String formatyCd, String naped, String szybkoscCd, String przekatnaEkranu,
			String systemKomputerowy, String architekturaSystemu, String klawiatura, String iloscZnakow,
			String urzadzenieWskazuj, String liczbaUsb2, String liczbaUsb3, String wyjSluchawkowe,
			String wejMikrofonowe, String hdmi, String vga, String portSieciowy, String inneSloty, String wysSzerGleb,
			String masa, String budowaBaterii, String najwCzasPracy, String iloscOgniw, String pojBaterii,
			String glosniki, String mikrofon, String kamera, String czytnikBio, String kompletZaw, String gwarancja,
			String oprogramowanie, BigDecimal cena, String fotka, int ilosc, Set<Foty> foties, Set<Fotaprzednia> fotaprzednias,
			Set<Zamowienie> zamowienies) {
		this.idLaptop = idLaptop;
		this.grafika = grafika;
		this.klient = klient;
		this.procesorChipset = procesorChipset;
		this.sieci = sieci;
		this.nazwaLaptopa = nazwaLaptopa;
		this.nazwaModelu = nazwaModelu;
		this.nrCzesci = nrCzesci;
		this.plytaGlowna = plytaGlowna;
		this.pamiecRam = pamiecRam;
		this.szybkoscPamieci = szybkoscPamieci;
		this.czestotliwoscTaktowaniaRam = czestotliwoscTaktowaniaRam;
		this.maksymalnaPamiec = maksymalnaPamiec;
		this.liczbaSlotowPam = liczbaSlotowPam;
		this.czytnikKart = czytnikKart;
		this.obslugiwanaKarta = obslugiwanaKarta;
		this.nosnikDanych = nosnikDanych;
		this.dostepDysku = dostepDysku;
		this.szybkoscNosnika = szybkoscNosnika;
		this.formatyCd = formatyCd;
		this.naped = naped;
		this.szybkoscCd = szybkoscCd;
		this.przekatnaEkranu = przekatnaEkranu;
		this.systemKomputerowy = systemKomputerowy;
		this.architekturaSystemu = architekturaSystemu;
		this.klawiatura = klawiatura;
		this.iloscZnakow = iloscZnakow;
		this.urzadzenieWskazuj = urzadzenieWskazuj;
		this.liczbaUsb2 = liczbaUsb2;
		this.liczbaUsb3 = liczbaUsb3;
		this.wyjSluchawkowe = wyjSluchawkowe;
		this.wejMikrofonowe = wejMikrofonowe;
		this.hdmi = hdmi;
		this.vga = vga;
		this.portSieciowy = portSieciowy;
		this.inneSloty = inneSloty;
		this.wysSzerGleb = wysSzerGleb;
		this.masa = masa;
		this.budowaBaterii = budowaBaterii;
		this.najwCzasPracy = najwCzasPracy;
		this.iloscOgniw = iloscOgniw;
		this.pojBaterii = pojBaterii;
		this.glosniki = glosniki;
		this.mikrofon = mikrofon;
		this.kamera = kamera;
		this.czytnikBio = czytnikBio;
		this.kompletZaw = kompletZaw;
		this.gwarancja = gwarancja;
		this.oprogramowanie = oprogramowanie;
		this.cena = cena;
		this.fotka = fotka;
		this.ilosc = ilosc;
		this.foties = foties;
		this.fotaprzednias = fotaprzednias;
		this.zamowienies = zamowienies;
	}

	public int getIdLaptop() {
		return this.idLaptop;
	}

	public void setIdLaptop(int idLaptop) {
		this.idLaptop = idLaptop;
	}

	public Grafika getGrafika() {
		return this.grafika;
	}

	public void setGrafika(Grafika grafika) {
		this.grafika = grafika;
	}

	public Klient getKlient() {
		return this.klient;
	}

	public void setKlient(Klient klient) {
		this.klient = klient;
	}

	public ProcesorChipset getProcesorChipset() {
		return this.procesorChipset;
	}

	public void setProcesorChipset(ProcesorChipset procesorChipset) {
		this.procesorChipset = procesorChipset;
	}

	public Sieci getSieci() {
		return this.sieci;
	}

	public void setSieci(Sieci sieci) {
		this.sieci = sieci;
	}

	public String getNazwaLaptopa() {
		return this.nazwaLaptopa;
	}

	public void setNazwaLaptopa(String nazwaLaptopa) {
		this.nazwaLaptopa = nazwaLaptopa;
	}

	public String getNazwaModelu() {
		return this.nazwaModelu;
	}

	public void setNazwaModelu(String nazwaModelu) {
		this.nazwaModelu = nazwaModelu;
	}

	public String getNrCzesci() {
		return this.nrCzesci;
	}

	public void setNrCzesci(String nrCzesci) {
		this.nrCzesci = nrCzesci;
	}

	public String getPlytaGlowna() {
		return this.plytaGlowna;
	}

	public void setPlytaGlowna(String plytaGlowna) {
		this.plytaGlowna = plytaGlowna;
	}

	public String getPamiecRam() {
		return this.pamiecRam;
	}

	public void setPamiecRam(String pamiecRam) {
		this.pamiecRam = pamiecRam;
	}

	public String getSzybkoscPamieci() {
		return this.szybkoscPamieci;
	}

	public void setSzybkoscPamieci(String szybkoscPamieci) {
		this.szybkoscPamieci = szybkoscPamieci;
	}

	public String getCzestotliwoscTaktowaniaRam() {
		return this.czestotliwoscTaktowaniaRam;
	}

	public void setCzestotliwoscTaktowaniaRam(String czestotliwoscTaktowaniaRam) {
		this.czestotliwoscTaktowaniaRam = czestotliwoscTaktowaniaRam;
	}

	public String getMaksymalnaPamiec() {
		return this.maksymalnaPamiec;
	}

	public void setMaksymalnaPamiec(String maksymalnaPamiec) {
		this.maksymalnaPamiec = maksymalnaPamiec;
	}

	public String getLiczbaSlotowPam() {
		return this.liczbaSlotowPam;
	}

	public void setLiczbaSlotowPam(String liczbaSlotowPam) {
		this.liczbaSlotowPam = liczbaSlotowPam;
	}

	public String getCzytnikKart() {
		return this.czytnikKart;
	}

	public void setCzytnikKart(String czytnikKart) {
		this.czytnikKart = czytnikKart;
	}

	public String getObslugiwanaKarta() {
		return this.obslugiwanaKarta;
	}

	public void setObslugiwanaKarta(String obslugiwanaKarta) {
		this.obslugiwanaKarta = obslugiwanaKarta;
	}

	public String getNosnikDanych() {
		return this.nosnikDanych;
	}

	public void setNosnikDanych(String nosnikDanych) {
		this.nosnikDanych = nosnikDanych;
	}

	public String getDostepDysku() {
		return this.dostepDysku;
	}

	public void setDostepDysku(String dostepDysku) {
		this.dostepDysku = dostepDysku;
	}

	public String getSzybkoscNosnika() {
		return this.szybkoscNosnika;
	}

	public void setSzybkoscNosnika(String szybkoscNosnika) {
		this.szybkoscNosnika = szybkoscNosnika;
	}

	public String getFormatyCd() {
		return this.formatyCd;
	}

	public void setFormatyCd(String formatyCd) {
		this.formatyCd = formatyCd;
	}

	public String getNaped() {
		return this.naped;
	}

	public void setNaped(String naped) {
		this.naped = naped;
	}

	public String getSzybkoscCd() {
		return this.szybkoscCd;
	}

	public void setSzybkoscCd(String szybkoscCd) {
		this.szybkoscCd = szybkoscCd;
	}

	public String getPrzekatnaEkranu() {
		return this.przekatnaEkranu;
	}

	public void setPrzekatnaEkranu(String przekatnaEkranu) {
		this.przekatnaEkranu = przekatnaEkranu;
	}

	public String getSystemKomputerowy() {
		return this.systemKomputerowy;
	}

	public void setSystemKomputerowy(String systemKomputerowy) {
		this.systemKomputerowy = systemKomputerowy;
	}

	public String getArchitekturaSystemu() {
		return this.architekturaSystemu;
	}

	public void setArchitekturaSystemu(String architekturaSystemu) {
		this.architekturaSystemu = architekturaSystemu;
	}

	public String getKlawiatura() {
		return this.klawiatura;
	}

	public void setKlawiatura(String klawiatura) {
		this.klawiatura = klawiatura;
	}

	public String getIloscZnakow() {
		return this.iloscZnakow;
	}

	public void setIloscZnakow(String iloscZnakow) {
		this.iloscZnakow = iloscZnakow;
	}

	public String getUrzadzenieWskazuj() {
		return this.urzadzenieWskazuj;
	}

	public void setUrzadzenieWskazuj(String urzadzenieWskazuj) {
		this.urzadzenieWskazuj = urzadzenieWskazuj;
	}

	public String getLiczbaUsb2() {
		return this.liczbaUsb2;
	}

	public void setLiczbaUsb2(String liczbaUsb2) {
		this.liczbaUsb2 = liczbaUsb2;
	}

	public String getLiczbaUsb3() {
		return this.liczbaUsb3;
	}

	public void setLiczbaUsb3(String liczbaUsb3) {
		this.liczbaUsb3 = liczbaUsb3;
	}

	public String getWyjSluchawkowe() {
		return this.wyjSluchawkowe;
	}

	public void setWyjSluchawkowe(String wyjSluchawkowe) {
		this.wyjSluchawkowe = wyjSluchawkowe;
	}

	public String getWejMikrofonowe() {
		return this.wejMikrofonowe;
	}

	public void setWejMikrofonowe(String wejMikrofonowe) {
		this.wejMikrofonowe = wejMikrofonowe;
	}

	public String getHdmi() {
		return this.hdmi;
	}

	public void setHdmi(String hdmi) {
		this.hdmi = hdmi;
	}

	public String getVga() {
		return this.vga;
	}

	public void setVga(String vga) {
		this.vga = vga;
	}

	public String getPortSieciowy() {
		return this.portSieciowy;
	}

	public void setPortSieciowy(String portSieciowy) {
		this.portSieciowy = portSieciowy;
	}

	public String getInneSloty() {
		return this.inneSloty;
	}

	public void setInneSloty(String inneSloty) {
		this.inneSloty = inneSloty;
	}

	public String getWysSzerGleb() {
		return this.wysSzerGleb;
	}

	public void setWysSzerGleb(String wysSzerGleb) {
		this.wysSzerGleb = wysSzerGleb;
	}

	public String getMasa() {
		return this.masa;
	}

	public void setMasa(String masa) {
		this.masa = masa;
	}

	public String getBudowaBaterii() {
		return this.budowaBaterii;
	}

	public void setBudowaBaterii(String budowaBaterii) {
		this.budowaBaterii = budowaBaterii;
	}

	public String getNajwCzasPracy() {
		return this.najwCzasPracy;
	}

	public void setNajwCzasPracy(String najwCzasPracy) {
		this.najwCzasPracy = najwCzasPracy;
	}

	public String getIloscOgniw() {
		return this.iloscOgniw;
	}

	public void setIloscOgniw(String iloscOgniw) {
		this.iloscOgniw = iloscOgniw;
	}

	public String getPojBaterii() {
		return this.pojBaterii;
	}

	public void setPojBaterii(String pojBaterii) {
		this.pojBaterii = pojBaterii;
	}

	public String getGlosniki() {
		return this.glosniki;
	}

	public void setGlosniki(String glosniki) {
		this.glosniki = glosniki;
	}

	public String getMikrofon() {
		return this.mikrofon;
	}

	public void setMikrofon(String mikrofon) {
		this.mikrofon = mikrofon;
	}

	public String getKamera() {
		return this.kamera;
	}

	public void setKamera(String kamera) {
		this.kamera = kamera;
	}

	public String getCzytnikBio() {
		return this.czytnikBio;
	}

	public void setCzytnikBio(String czytnikBio) {
		this.czytnikBio = czytnikBio;
	}

	public String getKompletZaw() {
		return this.kompletZaw;
	}

	public void setKompletZaw(String kompletZaw) {
		this.kompletZaw = kompletZaw;
	}

	public String getGwarancja() {
		return this.gwarancja;
	}

	public void setGwarancja(String gwarancja) {
		this.gwarancja = gwarancja;
	}

	public String getOprogramowanie() {
		return this.oprogramowanie;
	}

	public void setOprogramowanie(String oprogramowanie) {
		this.oprogramowanie = oprogramowanie;
	}

	public BigDecimal getCena() {
		return this.cena;
	}

	public void setCena(BigDecimal cena) {
		this.cena = cena;
	}

	public String getFotka() {
		return this.fotka;
	}

	public void setFotka(String fotka) {
		this.fotka = fotka;
	}

	public int getIlosc() {
		return ilosc;
	}

	public void setIlosc(int ilosc) {
		this.ilosc = ilosc;
	}

	public Set<Foty> getFoties() {
		return this.foties;
	}

	public void setFoties(Set<Foty> foties) {
		this.foties = foties;
	}

	public Set<Fotaprzednia> getFotaprzednias() {
		return this.fotaprzednias;
	}

	public void setFotaprzednias(Set<Fotaprzednia> fotaprzednias) {
		this.fotaprzednias = fotaprzednias;
	}

	public Set<Zamowienie> getZamowienies() {
		return this.zamowienies;
	}

	public void setZamowienies(Set<Zamowienie> zamowienies) {
		this.zamowienies = zamowienies;
	}

}
